### ISSUE TITLE
4 spaces needed in readme example

### ISSUE THREAD

**Issue by NorseGaud** [chef/anka-buildkite-plugin#17]
# Describe the problem

Turns out you need four spaces for options under the plugins which are defined as a list item:

Two spaces works if not a list item. Problem is that plugins can be loaded out of order.
```
steps:
  - command: make test
    plugins:
      chef/anka#v0.5.1:
        vm-name: macos-base-10.14
```

Two spaces does not work if it's a list item
```
steps:
  - command: make test
    plugins:
      - chef/anka#v0.5.1:
        vm-name: macos-base-10.14
```

Four spaces does work if list item.
```
steps:
  - command: make test
    plugins:
      - chef/anka#v0.5.1:
          vm-name: macos-base-10.14
```

Need to update the readme.
